# Generated by Django 5.1.1 on 2024-11-02 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsself',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photo=/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Addphoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo=/%Y/%m/%d')),
                ('addphoto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsself.newsself')),
            ],
        ),
    ]
