# Generated by Django 5.1.1 on 2024-10-05 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesatu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insvid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('video', models.CharField(max_length=890)),
                ('insvid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homesatu.homesatu')),
            ],
        ),
    ]
