# Generated by Django 5.1.1 on 2024-10-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesatu', '0003_rename_insvid_insvid_podcast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insvid',
            old_name='podcast',
            new_name='homesatu',
        ),
    ]
