# Generated by Django 5.1.1 on 2024-10-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesatu', '0004_rename_podcast_insvid_homesatu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insvid',
            old_name='homesatu',
            new_name='podcast',
        ),
    ]
