# Generated by Django 5.1.1 on 2024-10-05 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesatu', '0006_remove_insvid_podcast_homesatu_pcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesatu',
            name='pcat',
        ),
        migrations.AddField(
            model_name='insvid',
            name='podcast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homesatu.homesatu'),
        ),
    ]
