# Generated by Django 5.1.1 on 2024-10-27 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesatu', '0007_remove_homesatu_pcat_insvid_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='homesatu',
            name='category_homesatu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homesatu.category'),
        ),
    ]
