# Generated by Django 5.1.1 on 2024-10-29 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesatu', '0008_category_homesatu_category_homesatu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homesatu',
            name='category_homesatu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homesatu.category'),
        ),
    ]
