# Generated by Django 5.1.1 on 2025-01-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesatu', '0009_alter_category_name_alter_homesatu_category_homesatu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insvid',
            name='video',
            field=models.FileField(upload_to='video=/%Y/%m/%d'),
        ),
    ]
